name: Create GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: "Name of the new repository"
        required: true
        type: string
      description:
        description: "Description of the repository"
        required: false
        type: string
      private:
        description: "Make repository private"
        required: false
        type: boolean
      port_context:
        description: "Port context (required by Port)"
        required: false
        type: string

permissions:
  contents: write

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Create repository
        run: |
          gh repo create ${{ github.repository_owner }}/${{ github.event.inputs.repo_name }} \
            --description "${{ github.event.inputs.description }}" \
            $([[ "${{ github.event.inputs.private }}" == "true" ]] && echo "--private" || echo "--public") \
            --confirm

      - name: Notify Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          baseUrl: https://api.getport.io
          runId: ${{ fromJson(inputs.port_context).runId }}
          logMessage: |
            Repository created successfully
          status: SUCCESS
