name: Create GitHub Repo

on:
  workflow_dispatch:
    inputs:
      repo_name:
        description: 'Name of the new repository'
        required: true
        type: string
      description:
        description: 'Description of the repository'
        required: false
        type: string
      private:
        description: 'Make repository private'
        required: false
        type: boolean
      port_context:
        description: 'Port internal context (not used)'
        required: false
        type: string

jobs:
  create-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Create repository via GitHub API
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_NAME: ${{ github.event.inputs.repo_name }}
          DESCRIPTION: ${{ github.event.inputs.description }}
          PRIVATE: ${{ github.event.inputs.private }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/orgs/MokshiAyaZensar/repos \
            -d "$(jq -n \
              --arg name "$REPO_NAME" \
              --arg description "$DESCRIPTION" \
              --argjson private "$PRIVATE" \
              '{name: $name, description: $description, private: $private}')"
